name: captcha-solver-fix
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2024.2.2=h56e8100_0
  - cuda-version=11.8=h70ddcb2_2
  - cudatoolkit=11.8.0=h09e9e62_13
  - cudnn=8.8.0.121=h84bb9a4_4
  - libffi=3.4.4=hd77b12b_0
  - libzlib=1.2.13=hcfcfb64_5
  - libzlib-wapi=1.2.13=hcfcfb64_5
  - openssl=3.2.1=hcfcfb64_0
  - pip=23.3.1=py310haa95532_0
  - python=3.10.13=he1021f5_0
  - setuptools=68.2.2=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=hcfcfb64_5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - flatbuffers==23.5.26
      - fonttools==4.49.0
      - gast==0.4.0
      - google-auth==2.28.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - h5py==3.10.0
      - idna==3.6
      - joblib==1.3.2
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.2
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.2.0
      - pillow==10.2.0
      - protobuf==3.19.6
      - pyarrow==15.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - six==1.16.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - wrapt==1.16.0
prefix: D:\dev\.venvs\captcha-solver-fix
